version: '3.8'

services:
  react-app:
    build:
      context: .
    container_name: react-app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    external: true