export const REST_API_BASE_URL_USER = import.meta.env.VITE_REST_API_BASE_URL_USER;
export const REST_API_BASE_URL_USER_AUTH = import.meta.env.VITE_REST_API_BASE_URL_USER_AUTH;

export const REST_API_BASE_URL_USER_PUBLIC = import.meta.env.VITE_REST_API_BASE_URL_USER_PUBLIC;
