name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Create .env.production file from secrets
      run: |
        echo "VITE_REST_API_BASE_URL_STAFF=${{ secrets.VITE_REST_API_BASE_URL_STAFF }}" >> .env.production
        echo "VITE_REST_API_BASE_URL_STAFF_AUTH=${{ secrets.VITE_REST_API_BASE_URL_STAFF_AUTH }}" >> .env.production
        echo "VITE_REST_API_BASE_URL_USER=${{ secrets.VITE_REST_API_BASE_URL_USER }}" > .env.production
        echo "VITE_REST_API_BASE_URL_USER_AUTH=${{ secrets.VITE_REST_API_BASE_URL_USER_AUTH }}" > .env.production
        echo "VITE_REST_API_BASE_URL_USER_PUBLIC=${{ secrets.VITE_REST_API_BASE_URL_USER_PUBLIC }}" > .env.production
        

    - name: Install dependencies
      run: npm ci

    - name: Build app with production env
      run: npm run build

    - name: Build Docker image
      run: docker build -t rname97/book-store-fe:latest .

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: docker push rname97/book-store-fe:latest