name: Build and Push Docker Image FE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image with detailed logs
        run: |
          docker build --progress=plain -t rname97/book-store-fe:latest .
          echo "Build finished. Checking /app/dist contents inside build stage:"
          docker build --target builder --progress=plain . | tee build.log
          
      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push rname97/book-store-fe:latest